Add filesystem cleanup to provisioning script
Signed-off-by: Jan Dubois <jan.dubois@suse.com>

diff --git a/src/assets/lima-config.yaml b/src/assets/lima-config.yaml
--- a/src/assets/lima-config.yaml
+++ b/src/assets/lima-config.yaml
@@ -7,9 +7,17 @@ firmware:
 containerd:
   system: false
   user: false
+# Provisioning scripts run on every boot, not just initial VM provisioning.
 provision:
-- # This sets up the K3s persistent volumes.
-  # It is run on every boot, not just initial VM provisioning.
+- # Clean up filesystems
+  mode: system
+  script: |
+    #!/bin/sh
+    set -o errexit -o nounset -o xtrace
+    # During boot is the only safe time to delete old k3s versions.
+    rm -rf /var/lib/rancher/k3s/data
+    # Delete all tmp files older than 3 days.
+    find /tmp -depth -mtime +3 -delete
   mode: system
   script: |
     #!/bin/sh
