Switch back to cgroup v1 when running k3s 1.20.2 and earlier
Signed-off-by: Jan Dubois <jan.dubois@suse.com>

diff --git a/pkg/rancher-desktop/assets/lima-config.yaml b/pkg/rancher-desktop/assets/lima-config.yaml
--- a/pkg/rancher-desktop/assets/lima-config.yaml
+++ b/pkg/rancher-desktop/assets/lima-config.yaml
@@ -38,6 +38,19 @@ provision:
     fi
     umount /bootfs
     rmdir /bootfs
+- # make sure we booted with the right cgroup mode; k3s versions before 1.20.4 only support cgroup v1
+  mode: system
+  script: |
+    #!/bin/sh
+    set -o errexit -o nounset -o xtrace
+    [[ "${RC_CGROUP_MODE:-}" =~ "unified|hybrid|legacy" ]] || exit 0
+    if ! grep -q -E "^#?rc_cgroup_mode=\"$RC_CGROUP_MODE\"" /etc/rc.conf; then
+      sed -i -E "s/^#?rc_cgroup_mode=\".*\"/rc_cgroup_mode=\"$RC_CGROUP_MODE\"/" /etc/rc.conf
+      # avoid reboot loop if sed failed for any reason
+      if grep -q -E "^rc_cgroup_mode=\"$RC_CGROUP_MODE\"" /etc/rc.conf; then
+        reboot
+      fi
+    fi
 - # return unused space from the data volume back to the host
   mode: system
   script: |
